baseURL = "https://c84dbf71.homelab-notes.pages.dev/"
languageCode = "en-us"
title = "Homelab Notes"
theme = ["github.com/adityatelange/hugo-PaperMod"]

[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  googleAnalytics = ""  # disables the broken partial error

  [menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 2

  [[menu.main]]
    name = "Network"
    url = "/network/"
    weight = 3

  [[menu.main]]
    name = "Scripts"
    url = "/scripts/"
    weight = 4

[params.homeInfoParams]
  Title = "Welcome to Homelab Notes"
  Content = """
  Central hub for documenting your homelab setup.

  - [First Post](/posts/first-post/)
  - [Welcome](/posts/welcome/)
  - [Media Stack Overview](/media/overview/)
  - [Network Notes](/network/index/)
  - [Script Library](/scripts/intro/)
  """
